# Generated by Django 5.0.1 on 2024-01-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_todoitem_todolistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistitem',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='todolistitem',
            name='completed',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('complete', models.BooleanField()),
                ('todoList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.todolistitem')),
            ],
        ),
    ]
