# Generated by Django 5.0.1 on 2024-01-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_title_todolistitem_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoListItem',
            new_name='ToDoList',
        ),
    ]
