# Generated by Django 5.0.1 on 2024-01-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_todolistitem_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
